# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: list change tickets
        uses: shundor/servicenow-actions@main
        id: snow
        with: 
          sn_host:  "${{ secrets.SN_HOST }}"
          sn_username: "${{ secrets.SN_USERNAME }}"
          sn_password: "${{ secrets.SN_PASSWORD }}"
          sn_client_id: "${{ secrets.SN_CLIENT_ID }}"
          sn_client_secret: "${{ secrets.SN_CLIENT_SECRET }}"
          sn_module: "servicenow.itsm.change_request_info"
          sn_module_params: |
            query:
            - state: new
      - name: Write to file
        uses: frdrwrt/write-to-file@v1.3
        with:
          filepath: output.json
          mode: 0777
          content: ${{ steps.snow.outputs.output }}
      - name: Display output
        shell: bash
        run: |
            jq '.plays[].tasks[].hosts.localhost.records[]' output.json   
